-- Esta migração está vazia porque a função RPC `confirm_delivery_order` foi removida.
-- A lógica agora é tratada diretamente no frontend através da mutação `updateStatusMutation`.
-- Manter este arquivo de migração vazio garante a consistência do histórico de migrações.